version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      next:
        patterns:
          - "next*"
      wagmi:
        patterns:
          - "wagmi*"
          - "viem*"
          - "@wagmi/*"

  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  # Circuits dependencies
  - package-ecosystem: "npm"
    directory: "/circuits"
    schedule:
      interval: "monthly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"



